### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [ghsafaei/Orbit-of-a-stellar-object-around-the-galaxy#2]
I suggest adding topics such as `astronomy` to the About section at https://github.com/ghsafaei/Orbit-of-a-stellar-object-around-the-galaxy.

**Comment by ghsafaei** [comment]
Thank you for your good suggestion. done.

*******************************************************
Ghasem Safaei,
 Postdoctoral Researcher in Astrophysics,
 Department of Physics, Institute for Advanced Studies in Basic Sciences
(IASBS),
 444 Prof.  Yousef Sobouti Blvd., Zanjan 45137 -  66731,  Iran.
Home: No 67, the first Dead end, Shahid Evazmohammadi
Alley, Chaman Quarter, Shahid Motahhari St. Abhar, Zanjan-Iran
 P.O.Box: 45617-17957
 Cell-phone:   +98-9911943652
 Emails: ***@***.***      ***@***.***
***@***.***
Skype: gh.safaei
*******************************************************

**Comment by Beliavsky** [comment]
There should be an astrophysics tag that can be searched. How to add a topic is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by ghsafaei** [comment]
Thank you so much indeed! I think it is corrected now.


*******************************************************
Ghasem Safaei,
 Postdoctoral Researcher in Astrophysics,
 Department of Physics, Institute for Advanced Studies in Basic Sciences
(IASBS),
 444 Prof.  Yousef Sobouti Blvd., Zanjan 45137 -  66731,  Iran.
Home: No 67, the first Dead end, Shahid Evazmohammadi
Alley, Chaman Quarter, Shahid Motahhari St. Abhar, Zanjan-Iran
 P.O.Box: 45617-17957
 Cell-phone:   +98-9911943652
 Emails: ***@***.***      ***@***.***
***@***.***
Skype: gh.safaei
*******************************************************
